#!/bin/sh

export PATH="$HOME/local_packages/bin:$PATH"

running () {
    ps axco cmd | grep "^$1$" > /dev/null 
}

exists () {
    which $1 > /dev/null
}

start_if_not_running () {
    if running $1;
    then
        echo "$1 already running"
    else
        if exists $1;
        then
            $* &
            echo "$1 started"
        else
            echo "$1 not found"
        fi
    fi

}

start_if_not_running emacs
start_if_not_running gnome-terminal
start_if_not_running firefox
start_if_not_running rofi -modi "window,run,ssh" -key-window mod4+s -sidebar-mode
