#!/bin/sh

export PATH="$HOME/local_packages/bin:$PATH"

running () {
    ps axco cmd | grep "^$1$" > /dev/null 
}

exists () {
    which $1 > /dev/null
}

start_if_not_running () {
    if running $1;
    then
        echo "$1 already running"
    else
        if exists $1;
        then
            $* &
            echo "$1 started"
        else
            echo "$1 not found"
        fi
    fi

}

# Merge Xresources file, need to this since LightDM merges
# Xresources using -nocpp option [https://bugs.launchpad.net/lightdm/+bug/1084885]
# thus any preprocessor statements are ignored

xrdb -merge ~/.Xresources

# uxterm is shell script wrapper around xterm which basically just execs xterm,
# so we cannot check whether uxterm is running, using the current function and
# should check the state of xterm instead
if ! running xterm
then
    uxterm &
fi

start_if_not_running emacs
start_if_not_running firefox
start_if_not_running rofi -key-window mod4+s
# start_if_not_running artha
