#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"

running () {
    ps -ef | grep -v grep | grep "$1" | awk -F ' ' '{print $NF}' | awk -F '/' '{print $NF}' | grep "^$1$" > /dev/null
}

exists () {
    which $1 > /dev/null
}

start_if_not_running () {
    process=$1
    program=$1

    if [ -n "$2" ] ; then
        program=$2
        shift
    fi

    if running $process;
    then
        echo "$program already running"
    else
        if exists $program;
        then
            $* &
            echo "$program started"
        else
            echo "$program not found"
        fi
    fi

}

# Merge Xresources file, need to this since LightDM merges
# Xresources using -nocpp option [https://bugs.launchpad.net/lightdm/+bug/1084885]
# thus any preprocessor statements are ignored

xrdb -merge ~/.Xresources

start_if_not_running gnome-terminal-server gnome-terminal
start_if_not_running emacs
start_if_not_running firefox
start_if_not_running artha 

if [ -f ~/.xmonad/startup-hook-private ]
then
    . ~/.xmonad/startup-hook-private
fi
