# Make the shell aware of locally installed packages
export PATH="$HOME/.local/bin/:$HOME/.local/sbin/:$PATH"
export CPATH="$HOME/.local/include/:$CPATH"
export PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"
export LD_RUN_PATH="$HOME/.local/lib:$HOME/.local/lib64:$LD_RUN_PATH"
export LD_LIBRARY_PATH="$HOME/.local/lib:$HOME/.local/lib64:$LD_LIBRARY_PATH"
export LIBRARY_PATH="$HOME/.local/lib:$HOME/.local/lib64:$LIBRARY_PATH"
export ACLOCAL_PATH="$HOME/.local/share/aclocal/:$ACLOCAL_PATH"
export MANPATH="$HOME/.local/share/man:$MANPATH"

if which wmctrl &> /dev/null ; then
    if wmctrl -m 2>/dev/null | head -n 1 | awk -F ':' '{print $2}' | grep -q xmonad ; then
        export _JAVA_AWT_WM_NONREPARENTING=1
    fi
fi

if [ -z "$XDG_DATA_DIRS" ] ; then
    export XDG_DATA_DIRS="$HOME/.local/share"
else
    export XDG_DATA_DIRS="$HOME/.local/share:$XDG_DATA_DIRS"
fi

if [[ -f ~/.zshenv-private ]] ; then
    source ~/.zshenv-private
fi
